### ISSUE TITLE
Cache node modules for CI build.

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-web-app#13]
We can probably speed up the build by caching the `node_modules` directory. This can be accomplished by adding the following to `.travis.yml`.

```YAML
cache:
  directories:
    - node_modules
```
